### ISSUE TITLE
开机自启动弹窗

### ISSUE THREAD

**Issue by BeginnerSlob** [ottercorp/Dalamud.Updater#4]
弹窗如下：
![_I7K@GPG_YYWAS`_C7E@_7T](https://github.com/ottercorp/Dalamud.Updater/assets/1858088/1196fe61-3f2a-4e05-972b-1e351fd84b3a)

版本如下：
![086{IC~}AI`K8MV$0I917 9](https://github.com/ottercorp/Dalamud.Updater/assets/1858088/55da0f7e-f2e6-45ee-ab25-293a0489c380)

原因未知
使用环境，WIN11专业版22H2

**Comment by Bluefissure** [comment]
请删除同目录下的.config文件后重试
